import type { IPCReply, ParentToWorker } from './protocol';
type ReplyHandler = (reply: IPCReply) => void;
declare class YunzaiManager {
    private worker;
    private ready;
    private replyHandlers;
    private doneHandlers;
    private restartCount;
    private maxRestarts;
    private restartTimer;
    get isInstalled(): boolean;
    get isRunning(): boolean;
    get isReady(): boolean;
    getStatus(): string;
    install(repoUrl?: string): Promise<void>;
    update(): Promise<string>;
    start(): Promise<void>;
    stop(): Promise<void>;
    restart(): Promise<void>;
    send(msg: ParentToWorker): void;
    onReply(handler: ReplyHandler): () => void;
    onDone(handler: (done: any) => void): () => void;
    private handleMessage;
    private git;
    private npmInstall;
    installDeps(): Promise<string>;
    private ensureWorkspaces;
    private ensureMiaoPlugin;
}
export declare const manager: YunzaiManager;
export {};
